import { useState } from "react";
import useApi from "../hooks/useApi";
import { endpoints } from "../services/api";
import { useToast } from "../context/ToastContext";

import {
  PageHeader,
  DataTable,
  LoadingSpinner,
  ErrorState,
  RiskBadge,
  SearchBar,
  ConfirmationModal,
} from "../components";

import { dt } from "../utils/format";

const FILTERS = [
  { label: "All", value: "" },
  { label: "Open", value: "OPEN" },
  { label: "Investigating", value: "INVESTIGATING" },
  { label: "Resolved", value: "RESOLVED" },
  { label: "False Positive", value: "FALSE_POSITIVE" },
];

export default function CaseManagement() {
  const { toast } = useToast();

  const { data, loading, error, refresh } = useApi(() => endpoints.cases(), []);

  const [q, setQ] = useState("");
  const [status, setStatus] = useState("");
  const [modal, setModal] = useState(null);

  if (loading) {
    return <LoadingSpinner label="Loading cases..." />;
  }

  if (error) {
    return <ErrorState error={error} onRetry={refresh} />;
  }

  /*
   * Backend:
   *
   * GET /api/fraud/cases
   *
   * returns:
   *
   * [
   *   {
   *     case_id,
   *     type,
   *     severity,
   *     agent,
   *     risk_score,
   *     reference,
   *     status,
   *     assigned_reviewer,
   *     resolution_note,
   *     created_at
   *   }
   * ]
   */

  const cases = Array.isArray(data) ? data : data?.cases || [];

  /*
   * Search + status filtering
   */
  const rows = cases.filter((c) => {
    const matchesStatus = !status || c.status === status;

    const searchText = [
      c.case_id,
      c.type,
      c.severity,
      c.agent,
      c.reference,
      c.status,
      c.assigned_reviewer,
      c.resolution_note,
    ]
      .filter(Boolean)
      .join(" ")
      .toLowerCase();

    const matchesSearch = !q || searchText.includes(q.toLowerCase());

    return matchesStatus && matchesSearch;
  });

  /*
   * Execute case action
   */
  const act = async () => {
    if (!modal) return;

    try {
      let body = {};

      if (modal.action === "resolve") {
        body = {
          decision: "RESOLVED",
          note: "Case resolved by reviewer",
        };
      }

      if (modal.action === "escalate") {
        body = {
          note: "Case escalated by reviewer",
        };
      }

      if (modal.action === "assign") {
        body = {
          note: "Case assigned for investigation",
        };
      }

      console.log("CASE ACTION:", modal.action, modal.id, body);

      await endpoints.caseAction(modal.id, modal.action, body);

      const actionLabel = {
        resolve: "resolved",
        escalate: "escalated",
        assign: "assigned",
      }[modal.action];

      toast(`Case ${modal.id} ${actionLabel}`, "success");

      setModal(null);

      /*
       * Reload cases after action
       */
      refresh();
    } catch (e) {
      console.error("CASE ACTION ERROR:", e);

      toast(e.message || "Case action failed", "error");
    }
  };

  return (
    <div className="space-y-6">
      {/* =========================
          PAGE HEADER
         ========================= */}

      <PageHeader
        title="Case Management"
        description="Review, investigate, resolve and escalate fraud cases generated by the trust and safety agents."
      />

      {/* =========================
          SEARCH + FILTER
         ========================= */}

      <div className="card">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div className="w-full lg:max-w-md">
            <SearchBar
              value={q}
              onChange={setQ}
              placeholder="Search cases, agents, references..."
            />
          </div>

          {/* Do NOT use FilterPanel here */}
          <select
            className="input lg:w-52"
            value={status}
            onChange={(e) => setStatus(e.target.value)}
          >
            {FILTERS.map((filter) => (
              <option key={filter.value} value={filter.value}>
                {filter.label}
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* =========================
          CASE SUMMARY
         ========================= */}

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <div className="card">
          <p className="text-sm text-slate-400">Total Cases</p>

          <p className="mt-2 text-2xl font-bold text-white">{cases.length}</p>
        </div>

        <div className="card">
          <p className="text-sm text-slate-400">Open</p>

          <p className="mt-2 text-2xl font-bold text-white">
            {cases.filter((c) => c.status === "OPEN").length}
          </p>
        </div>

        <div className="card">
          <p className="text-sm text-slate-400">Investigating</p>

          <p className="mt-2 text-2xl font-bold text-white">
            {cases.filter((c) => c.status === "INVESTIGATING").length}
          </p>
        </div>

        <div className="card">
          <p className="text-sm text-slate-400">Resolved</p>

          <p className="mt-2 text-2xl font-bold text-white">
            {
              cases.filter(
                (c) => c.status === "RESOLVED" || c.status === "FALSE_POSITIVE",
              ).length
            }
          </p>
        </div>
      </div>

      {/* =========================
          CASE TABLE
         ========================= */}

      <div className="card">
        <DataTable
          columns={[
            {
              key: "case_id",
              label: "Case",
              render: (r) => (
                <div>
                  <p className="font-medium text-white">{r.case_id}</p>

                  <p className="text-xs text-slate-500">
                    {r.reference || "No reference"}
                  </p>
                </div>
              ),
            },

            {
              key: "type",
              label: "Case Type",
              render: (r) => (
                <span className="text-sm text-slate-200">
                  {r.type || "Unknown"}
                </span>
              ),
            },

            {
              key: "agent",
              label: "Agent",
              render: (r) => (
                <span className="text-sm text-slate-300">
                  {r.agent || "Unknown"}
                </span>
              ),
            },

            {
              key: "severity",
              label: "Risk",
              render: (r) => <RiskBadge level={r.severity || "MEDIUM"} />,
            },

            {
              key: "risk_score",
              label: "Score",
              render: (r) => (
                <span className="font-semibold text-white">
                  {Number(r.risk_score || 0).toFixed(0)}
                </span>
              ),
            },

            {
              key: "status",
              label: "Status",
              render: (r) => (
                <span
                  className={`
                    inline-flex rounded-full
                    px-2.5 py-1
                    text-xs font-medium
                    ${
                      r.status === "OPEN"
                        ? "bg-red-500/10 text-red-400"
                        : r.status === "INVESTIGATING"
                          ? "bg-yellow-500/10 text-yellow-400"
                          : r.status === "RESOLVED"
                            ? "bg-green-500/10 text-green-400"
                            : r.status === "FALSE_POSITIVE"
                              ? "bg-slate-500/10 text-slate-400"
                              : "bg-white/10 text-slate-300"
                    }
                  `}
                >
                  {r.status || "UNKNOWN"}
                </span>
              ),
            },

            {
              key: "assigned_reviewer",
              label: "Reviewer",
              render: (r) => (
                <span className="text-sm text-slate-400">
                  {r.assigned_reviewer || "Unassigned"}
                </span>
              ),
            },

            {
              key: "created_at",
              label: "Created",
              render: (r) => (
                <span className="text-sm text-slate-400">
                  {dt(r.created_at)}
                </span>
              ),
            },

            {
              key: "actions",
              label: "Actions",
              render: (r) => {
                const closed =
                  r.status === "RESOLVED" || r.status === "FALSE_POSITIVE";

                if (closed) {
                  return (
                    <span className="text-xs text-slate-500">No actions</span>
                  );
                }

                return (
                  <div className="flex flex-wrap gap-2">
                    <button
                      className="btn-ghost !px-2 !py-1"
                      onClick={() =>
                        setModal({
                          id: r.case_id,
                          action: "assign",
                        })
                      }
                    >
                      Assign
                    </button>

                    <button
                      className="btn-ghost !px-2 !py-1"
                      onClick={() =>
                        setModal({
                          id: r.case_id,
                          action: "resolve",
                        })
                      }
                    >
                      Resolve
                    </button>

                    <button
                      className="btn-ghost !px-2 !py-1"
                      onClick={() =>
                        setModal({
                          id: r.case_id,
                          action: "escalate",
                        })
                      }
                    >
                      Escalate
                    </button>
                  </div>
                );
              },
            },
          ]}
          rows={rows}
        />

        {rows.length === 0 && (
          <div className="p-8 text-center">
            <p className="text-sm text-slate-400">No cases found.</p>
          </div>
        )}
      </div>

      {/* =========================
          CONFIRMATION MODAL
         ========================= */}

      <ConfirmationModal
        open={!!modal}
        title="Confirm case action"
        onCancel={() => setModal(null)}
        onConfirm={act}
      >
        <div className="space-y-2">
          <p className="text-sm text-slate-300">
            You are about to{" "}
            <span className="font-semibold text-white">{modal?.action}</span>{" "}
            case <span className="font-semibold text-white">{modal?.id}</span>.
          </p>

          <p className="text-xs text-slate-500">
            This action will be recorded in the immutable audit trail.
          </p>
        </div>
      </ConfirmationModal>
    </div>
  );
}
